### ISSUE TITLE
Add a note about set toggle edit mode invalidation

### ISSUE THREAD

**Issue by danielberlinger** [Morningstar-Engineering/MC6-MKII-Midi-Controller#13]
https://github.com/Morningstar-Engineering/MC6-MKII-Midi-Controller/blob/61b00eada78f3582635efdc6fe800bffbe233b73/site/glossary/07-midi-type-glossary/index.html#L222

For set toggle, I stumbled across (in the forums) that set toggle is switched off when you're in edit mode. Since I've only edited using the Mac software, this was confusing. That is, that set toggle wasn't working seemed odd, nor could I understand what to do to make it work until I stumbled on a note in the forum that it doesn't work in edit mode).

I'm suggesting that a note be added here to the docs (at least) informing users of this feature.

"Note: Set toggle does not operate while the unit is in edit mode. To see the effects of set toggle, exit edit mode." Or something to that effect.

**Comment by tyzjames** [comment]
Thanks for bringing this up, Daniel. We have updated the documentation.
