### ISSUE TITLE
MC6 MkII v3_8_0 Beta_12_8_20

### ISSUE THREAD

**Issue by applekor** [Morningstar-Engineering/MC6-MKII-Midi-Controller#24]
I am using the latest beta firmware (v.3.8.0, 12-8-20) release on the MC6 MkII with a factory reset conducted under v3.7.3.  After removing power then reapplying power, a solid bar is displayed along the top row of the LCD. pushing footswitches does nothing and the unit will not enter the global configuration menu.  The staging editor attempts to connect to the MC6, but fails to complete the process.  Windows 10 Device Manager shows status as "working properly."  The MC6 functions normally after reflashing with v3.7.3.  Further attempts to flash to v3.8.0 (12-8-20) results in the same failure upon power cycle each time.  Prior to power cycle it appears to function normally.   Firmware v3.8.0 (12-4-20) loads and behaves normally before and after power cycle.

**Comment by tyzjames** [comment]
Hey @applekor , yes we just noticed the issue. It will work fine on first update, but when the power is cycled, the device cannot boot up. Please remove the backplate and press the reset button while uploading the 2020-12-04 firmware. We'll look into this issue now.

**Comment by tyzjames** [comment]
@applekor More info here: https://morningstarengineering.atlassian.net/wiki/spaces/MMS/pages/211746834/Firmware+Upload+Failure

Thanks for reporting this.

**Comment by applekor** [comment]
Reloading the 12-4-2020 firmware works fine without having to use the hardware reset button.

**Comment by tyzjames** [comment]
@applekor Thanks for the update. We have resolved the issue and are testing it now before posting the update.

**Comment by applekor** [comment]
@tyzjames  Sounds good.  You guys are good!

**Comment by tyzjames** [comment]
@applekor Fixed deployed to 2020-12-09 firmware. Thanks again!

**Comment by applekor** [comment]
Power cycle issue solved on my unit using the 12-9-2020 release.  Have a good day.
