### ISSUE TITLE
Restore loading of preset data into the editor with switch presses (removed in 3.8.4)

### ISSUE THREAD

**Issue by dkrieger** [Morningstar-Engineering/MC6-MKII-Midi-Controller#29]
From firmware 3.8.4 release notes:

> Loading of Preset data into the editor will no longer be done with switch presses, but only via the Editor drop-down menu.

This is a UX regression in my opinion, and a poll of users would probably show a significant number of others who preferred this behavior. The old behavior allowed for a significantly faster workflow.

**Comment by tyzjames** [comment]
Have added a "Editor Setting" tab in the editor so users can select their preference.
