### ISSUE TITLE
"Engage Preset" message type: allow engaging with current preset

### ISSUE THREAD

**Issue by dkrieger** [Morningstar-Engineering/MC6-MKII-Midi-Controller#30]
currently (3.8.4) one cannot send "Engage Preset" messages destined for the preset in which the message is defined.

use case: "No Action" action can be used for what I'll call "synthetic actions" that can be triggered by some other preset's "Engage Preset" message. If one could send "Engage Preset" messages targeting the same preset, these "synthetic actions" could be triggered by any preset _including_ the target preset.

put differently, "Engage Preset" messages open up a lot of automation potential, but the inability to automate the preset in which the message is sent from limits that potential.

**Comment by tyzjames** [comment]
thanks for bringing this up. Yes, a preset cannot currently engage itself. I think we can change this to "a engage preset message cannot engage the same preset with the same action". Have added it to our backlog to check

**Comment by tyzjames** [comment]
In v3.9 we have updated the feature to allow a preset to call itself, but not with the same action.
