### ISSUE TITLE
Wrong Asset listed

### ISSUE THREAD

**Issue by SkeemoFPV** [Morningstar-Engineering/MC6-MKII-Midi-Controller#31]
The latest assets for the MC6 mk2, ver 3.8.7 are actually for the MC8 and obviously do not work on the MC6.
![2FC70160-C673-4E66-93E0-EE182B328E79](https://user-images.githubusercontent.com/25980738/119258414-6d31e200-bbc1-11eb-9497-1a41f7842df4.jpeg)

**Comment by tyzjames** [comment]
Thanks! Have resolved this
